default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: onspecial_development
  username: george
  host: localhost
  port: 5432

test:
  <<: *default
  database: onspecial_test
  username: george
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# Required for SolidCable
cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# Required for SolidQueue
queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>